### ISSUE TITLE
Is the 'cancelButtonIndex' supposed to fire the onPress handler?

### ISSUE THREAD

**Issue by amtruenorth** [beefe/react-native-actionsheet#12]
When pressing the cancel button, my onPress handler function is firing (passing the index of my cancel button).  To prevent, I am doing this in my handler function:

```javascript
if (index !== CANCEL_INDEX) { 
  ...handler code here.
}
```

Is this normal behavior?

**Comment by xiaoyann** [comment]
Yes


发自网易邮箱 iPhone 版
On 11/08/2016 22:37, Adam Main wrote:

When pressing the cancel button, my onPress handler function is firing (passing the index of my cancel button). To prevent, I am doing this in my handler function:

if (index !==CANCEL_INDEX) { 
  ...handler code here.
}

Is this normal behavior?

**Comment by amtruenorth** [comment]
Thanks
