### ISSUE TITLE
Dynamically change actionsheet title

### ISSUE THREAD

**Issue by andruxnet** [beefe/react-native-actionsheet#18]
Is it possible to dynamically change the title for the action sheet?

For example, I have a ListView with several items, and I want that when the user presses on an item then the title would be set to a prop in that item

I tried this.ActionSheet.title = 'new title' but it doesn't work

**Comment by xiaoyann** [comment]
```js
<ActionSheet 
     title={this.state.title}
    onPress={() => this.setState({title: 'new title'})}
     ....
/>
```

**Comment by andruxnet** [comment]
Thanks, it didn't work but I found a workaround where I'm also able to modify the options, same use case, I want to show different options depending on state.

The way I'm doing it now is that I modified your show() method to accept a new set of options for the component, this way, you can use a different title and buttons altogether, I can submit a PR if you're interested in this, I'm just going to work out the android part and it will be ready.

It would end up something like this:

`    const actionSheetOptions = {
      title: this.state.userName,
      options: [
        'Cancel',
        `View profile`,
        `Block messages from ${this.state.userName}`,
      ],
      destructiveButtonIndex: 2
    }
    this.ActionSheet.show(actionSheetOptions)
`

**Comment by emmanuellmota** [comment]
Work if call show() after setState (callback) like this:

`
this.setState({actionSheetTitle: 'New Title'}, () => this.ActionSheet.show());
`

**Comment by dchersey** [comment]
@andruxnet I have the same need; would be interested in your PR if you still have it around!

**Comment by bmwertman** [comment]
I'm also in need of this functionality. I tried @emmanuellmota's solution but the action sheet closes without reopening.
