### ISSUE TITLE
我把actionsheet嵌入到子组件中，居然不是在屏幕底部出现，而是屏幕中间

### ISSUE THREAD

**Issue by CaveyChan** [beefe/react-native-actionsheet#2]
我想做点击子组件的按钮弹出actionsheet的效果，actionsheet在屏幕中间出现

![default](https://cloud.githubusercontent.com/assets/16031190/15467734/b38dfb0c-2112-11e6-9018-1132e49de0fd.jpg)

怎么解决？？？

**Comment by xiaoyann** [comment]
嗯，我看看，谢谢反馈

**Comment by xiaoyann** [comment]
问题已经修复，使用`2.0.0`版本

**Comment by CaveyChan** [comment]
刚刚卸载 重装了组件，但是我并没有看到问题被解决，
一个ListVIew，
Row封装成一个组件，
我要做的是点击这个Row组件中的一个按钮，弹出actionsheet，
我把actionsheet写入到Row组件的代码的下面，
问题是弹出后这个actionsheet出现在Row组件的底部，而不是屏幕的底部，

**Comment by xiaoyann** [comment]
是2.0.0？

**Comment by CaveyChan** [comment]
不好意思哈，刚才我没有升级成功，
现在升级2.0.0成功后，问题解决了，
谢谢分享

**Comment by xiaoyann** [comment]
😄
