### ISSUE TITLE
显示效果问题，可以给选项添加图标+文字效果吗？

### ISSUE THREAD

**Issue by luojinghui** [beefe/react-native-actionsheet#21]
我想在选项中引用icon图标，怎么添加呢。有没有解决方法。

**Comment by xiaoyann** [comment]
从新写一个吧 😄

**Comment by luojinghui** [comment]
@xiaoyann 你有类似的插件推荐吗。我找了好久没有~~~
或者是一行显示多个选项的效果，就是用作分享功能呢。求解

**Comment by xiaoyann** [comment]
很好实现的，使用RN提供的 modal，然后自己写下选项的样式

**Comment by xiaoyann** [comment]
看这里有吗 https://js.coach/react-native?search=share

**Comment by luojinghui** [comment]
@xiaoyann 非常感谢，还准备自己写啊。就用插件吧

**Comment by fukemy** [comment]
hi @luojinghui , can u share your git when u done it? I still searching but did not found any

**Comment by luojinghui** [comment]
> hi @luojinghui , can u share your git when u done it? I still searching but did not found any

too long，you can try to simulate the implementation using the popup component of the [ant-mobile-rn](https://rn.mobile.ant.design/components/modal-cn/)  library.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/12367406/180679953-eb291e7e-6fa9-4917-ba93-6caf8d76bc13.png">

**Comment by fukemy** [comment]
im using sheetview and design view like actionsheet, it's worked better
