### ISSUE TITLE
Render title as element

### ISSUE THREAD

**Issue by luco** [beefe/react-native-actionsheet#35]
Is it possible to render title as react.element?
It's defined in Docs, but when I try to set it, it gives me warning that title only accepts string as prop.

![image](https://user-images.githubusercontent.com/246373/29681622-a860e714-88de-11e7-90f8-92b873d16299.png)

**Comment by xiaoyann** [comment]
Which version do you use? The example running well without any exception.

**Comment by seavan** [comment]
@xiaoyann yes, this doesn't work on iOS at all (custom Element for title). any plans on fixing it?

**Comment by elengart** [comment]
Yes, please let us know if rendering <Text>option</Text> will be fixed for iOS ... thanks!
