### ISSUE TITLE
请问该组件支持自定义View吗？？

### ISSUE THREAD

**Issue by CaveyChan** [beefe/react-native-actionsheet#4]
![aaaaaaaaaa](https://cloud.githubusercontent.com/assets/16031190/15639222/a76363c8-265b-11e6-8e09-e454f049894a.jpg)

就是做类似上面的效果
该组件支持吗？

**Comment by xiaoyann** [comment]
现在不可以

**Comment by CaveyChan** [comment]
有支持的计划吗？如果近期有支持的计划，我就等待您版本的更新，否则只能自己写了

**Comment by xiaoyann** [comment]
暂时没计划
