### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by CaveyChan** [beefe/react-native-actionsheet#6]
当点击actionsheet的灰色背景时，自动调用了onPress函数，其index参数值为undefined，
我不知道你是故意这样设计，还是一个bug

个人认为点击actionsheet的灰色背景，不应该调用onPress函数，
即使调用，index参数值也应该和cancelButtonIndex值相同

**Comment by xiaoyann** [comment]
是有这个问题，马上修复。保持和 iOS 原生 ActionSheet 一致，调用 onPress，值为 cancelButtonIndex

**Comment by xiaoyann** [comment]
修复了，感谢反馈。

**Comment by CaveyChan** [comment]
我并没有看到bug被修复  v2.0.3

**Comment by xiaoyann** [comment]
你确定？
