### ISSUE TITLE
How to have multiple ActionSheets

### ISSUE THREAD

**Issue by tscrip** [beefe/react-native-actionsheet#68]
I would like to have 3 different action sheets with 3 different sets of options. How would you trigger a specific Action Sheets?

**Comment by tscrip** [comment]
You can just create a different ref for the second Action Sheet

**Comment by kookan107** [comment]
Can you show me a Example Code?

**Comment by ggdegreat** [comment]
This is a question or a guide on how to create multiple Action Sheet?
