### ISSUE TITLE
Error calling RCTEventEmitter.receiveTouches

### ISSUE THREAD

**Issue by vkupar** [beefe/react-native-actionsheet#71]
This error occures when I run `this.ActionSheet.show()` from **iOS**

Error calling RCTEventEmitter.receiveTouches

Unhandled JS Exception: Exception calling object as function: [object Object], 381 is not usable as a native methd argument (unknown file: 2206)

**Comment by rarenatoe** [comment]
This error occurs to me when I add the `<Text></Text>` tags to the title prop.

**Comment by lukebrandonfarrell** [comment]
@vatex @renato-bvdash Any update on this? It occurs when we pass a custom element to `options` on iOS.

**Comment by vkupar** [comment]
@lukebrandonfarrell I use this module for Android only. I used [ActionSheetIOS](https://docs.expo.io/versions/latest/react-native/actionsheetios) for iOS platform

**Comment by adescode** [comment]
> Error calling RCTEventEmitter.receiveTouches
> 
> Unhandled JS Exception: Exception calling object as function: [object Object], 381 is not usable as a native methd argument (unknown file: 2206)

if you are using a custom styling 
check your import it should 
**import { ActionSheetCustom as ActionSheet } from 'react-native-actionsheet';**
not  **import  ActionSheet from 'react-native-actionsheet';**
