### ISSUE TITLE
[Android]: Doesn't show on android

### ISSUE THREAD

**Issue by xphaul** [beefe/react-native-actionsheet#8]
`"react": "^0.14.5",
    "react-native": "^0.22.2",
    "react-native-actionsheet": "^2.0.3"`

this is my package.json . followed all the steps but it only shows red dot . thanks
@xiaoyann

**Comment by xiaoyann** [comment]
`react-native` should > 0.25.1

**Comment by xphaul** [comment]
@xiaoyann okay thanks . ill just use a dropdown . thanks
